### ISSUE TITLE
NZXT Smartdevice v2 support

### ISSUE THREAD

**Issue by tbaumann** [liquidctl/liquidtux#6]
Is anyone currently working on this?

I started some work. But it's very ugly cargo cult coding. And based on the now quite refactored `nzxt-smartdevice.c` driver.

**Comment by jonasmalacofilho** [comment]
I think you're the first.

Regarding the WIP V1 driver you used as a base, I'm having some trouble with the final details of the `pwm` stuff, hence the many changes.

(That device is fairly quirky, and lm-sensors `pwmconfig`/`fancontrol` [probably the cannonical consumers of those attributes]  aren't very tolerant).

Still, let me know how I can help.

**Comment by tbaumann** [comment]
I am going to be without my computer for a while. But I plan to get back to this...

**Comment by amezin** [comment]
@tbaumann I've written a driver for rgb&fan controller/smart device v2: https://github.com/amezin/nzxt-rgb-fan-controller-dkms
Could you test if it works for you (especially if you have the "smart device v2" and not "rgb&fan controller")? I'm planning to submit it to hwmon mailing list soon, so any testing would be really helpful.

**Comment by tbaumann** [comment]
@amezin wow, I love it.

Unfortunately my computer is currently in storage until I have finished my relocation.

**Comment by jonasmalacofilho** [comment]
I also merged amezin's driver (from/as of PR $8) into liquidtux. Closing this then.

Thanks again and, by the way, welcome to the org, @amezin!
